import { createContext, useContext, useState, useEffect } from 'react';
import type { ReactNode } from 'react';

type Language = 'en' | 'ru' | 'he';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
    en: {
        'dashboard': 'Dashboard',
        'add_transaction': 'Add Transaction',
        'profile': 'Profile',
        'logout': 'Logout',
        'login': 'Login',
        'register': 'Register',
        'settings': 'Settings',
        'theme': 'Theme',
        'language': 'Language',
        'english': 'English',
        'russian': 'Русский',
        'hebrew': 'עברית',
        'light': 'Light',
        'dark': 'Dark',
        'close': 'Close',
        'save': 'Save',
        'expense': 'Expense',
        'income': 'Income',
        'total_income': 'Total Income',
        'total_expenses': 'Total Expenses',
        'net_balance': 'Net Balance',
        'net': 'Net',
        'hi': 'Hi',
        'recent_transactions': 'Recent Transactions',
        'analytics': 'Analytics',
        'category': 'Category',
        'amount': 'Amount',
        'amount_placeholder': 'Enter amount',
        'date': 'Date',
        'notes': 'Notes',
        'note_placeholder': 'Add a note (optional)',
        'add': 'Add',
        'edit': 'Edit',
        'delete': 'Delete',
        'cancel': 'Cancel',
        'name': 'Name',
        'email': 'Email',
        'password': 'Password',
        'confirm_password': 'Confirm Password',
        'select_language': 'Select Language',
        'already_have_account': 'Already have an account? Login',
        'create_account': 'Create Account',
        'no_transactions': 'No transactions yet',
        'no_transactions_desc': 'Start tracking by adding a new transaction',
        'no_note': 'No note',
        'delete_confirm': 'Are you sure you want to delete this transaction?',
        'cat_food': 'Food',
        'cat_transport': 'Transport',
        'cat_home': 'Home',
        'cat_shopping': 'Shopping',
        'cat_health': 'Health',
        'cat_other': 'Other',
        'add_transaction_desc': 'Add an expense or income to track your finances',
        'edit_transaction': 'Edit Transaction',
        'edit_transaction_desc': 'Update your transaction details',
        'or': 'or',
        'login_with_google': 'Continue with Google',
        'register_with_google': 'Sign up with Google',
        'stats': 'Stats',
        'transactions': 'Transactions',
        'top_category': 'Top Category',
        'data_export': 'Data Export',
        'export_json': 'Export to JSON',
        'change': 'Change',
        'currency': 'Currency',
        'welcome_title': 'Welcome to FlowMoney',
        'welcome_lead': 'Track your expenses, visualize spending and reach your goals.',
        'go_to_dashboard': 'Go to Dashboard',
        'chart_by_category': 'By Category',
        'chart_income_vs_expenses': 'Income vs Expenses',
        'no_expense_data': 'No expense data',
        'no_data': 'No data',
        'current_currency': 'Current currency',
        'current_theme': 'Current theme',
        'toggle_theme': 'Toggle Theme',
        'categories': 'Categories',
        'add_category': 'New category name',
        'category_exists': 'Category already exists',
        'category_in_use': 'Category is used in transactions',
        'category_default': 'Default category cannot be deleted',
        'update_app': 'Update App',
        'auto': 'Auto',
    },
    ru: {
        'dashboard': 'Панель управления',
        'add_transaction': 'Добавить операцию',
        'profile': 'Профиль',
        'logout': 'Выход',
        'login': 'Вход',
        'register': 'Регистрация',
        'settings': 'Настройки',
        'theme': 'Тема',
        'language': 'Язык',
        'english': 'English',
        'russian': 'Русский',
        'hebrew': 'עברית',
        'light': 'Светлая',
        'dark': 'Тёмная',
        'close': 'Закрыть',
        'save': 'Сохранить',
        'expense': 'Расход',
        'income': 'Доход',
        'total_income': 'Всего доходов',
        'total_expenses': 'Всего расходов',
        'net_balance': 'Чистый баланс',
        'net': 'Итого',
        'hi': 'Привет',
        'recent_transactions': 'Последние операции',
        'analytics': 'Аналитика',
        'category': 'Категория',
        'amount': 'Сумма',
        'amount_placeholder': 'Введите сумму',
        'date': 'Дата',
        'notes': 'Заметка',
        'note_placeholder': 'Добавить заметку (необязательно)',
        'add': 'Добавить',
        'edit': 'Редактировать',
        'delete': 'Удалить',
        'cancel': 'Отмена',
        'name': 'Имя',
        'email': 'Email',
        'password': 'Пароль',
        'confirm_password': 'Подтвердите пароль',
        'select_language': 'Выберите язык',
        'already_have_account': 'Уже есть аккаунт? Вход',
        'create_account': 'Создать аккаунт',
        'no_transactions': 'Нет операций',
        'no_transactions_desc': 'Добавьте первую операцию для отслеживания',
        'no_note': 'Без заметки',
        'delete_confirm': 'Вы уверены, что хотите удалить эту операцию?',
        'cat_food': 'Еда',
        'cat_transport': 'Транспорт',
        'cat_home': 'Дом',
        'cat_shopping': 'Покупки',
        'cat_health': 'Здоровье',
        'cat_other': 'Другое',
        'add_transaction_desc': 'Добавьте расход или доход для учёта финансов',
        'edit_transaction': 'Редактировать операцию',
        'edit_transaction_desc': 'Обновите данные операции',
        'or': 'или',
        'login_with_google': 'Войти через Google',
        'register_with_google': 'Зарегистрироваться через Google',
        'stats': 'Статистика',
        'transactions': 'Операции',
        'top_category': 'Топ категория',
        'data_export': 'Экспорт данных',
        'export_json': 'Экспортировать в JSON',
        'change': 'Изменить',
        'currency': 'Валюта',
        'welcome_title': 'Добро пожаловать в FlowMoney',
        'welcome_lead': 'Отслеживайте расходы, анализируйте траты и достигайте финансовых целей.',
        'go_to_dashboard': 'Перейти к панели',
        'chart_by_category': 'По категориям',
        'chart_income_vs_expenses': 'Доходы и расходы',
        'no_expense_data': 'Нет данных о расходах',
        'no_data': 'Нет данных',
        'current_currency': 'Текущая валюта',
        'current_theme': 'Текущая тема',
        'toggle_theme': 'Сменить тему',
        'categories': 'Категории',
        'add_category': 'Название новой категории',
        'category_exists': 'Категория уже существует',
        'category_in_use': 'Категория используется в операциях',
        'category_default': 'Базовую категорию нельзя удалить',
        'update_app': 'Обновить приложение',
        'auto': 'Авто',
    },
    he: {
        'dashboard': 'לוח מחוונים',
        'add_transaction': 'הוסף עסקה',
        'profile': 'פרופיל',
        'logout': 'התנתקות',
        'login': 'כניסה',
        'register': 'הרשמה',
        'settings': 'הגדרות',
        'theme': 'ערכת נושא',
        'language': 'שפה',
        'english': 'English',
        'russian': 'Русский',
        'hebrew': 'עברית',
        'light': 'בהיר',
        'dark': 'אפל',
        'close': 'סגור',
        'save': 'שמור',
        'expense': 'הוצאה',
        'income': 'הכנסה',
        'total_income': 'סה"כ הכנסות',
        'total_expenses': 'סה"כ הוצאות',
        'net_balance': 'יתרה נקייה',
        'net': 'נטו',
        'hi': 'שלום',
        'recent_transactions': 'עסקאות אחרונות',
        'analytics': 'אנליטיקה',
        'category': 'קטגוריה',
        'amount': 'סכום',
        'amount_placeholder': 'הכנס סכום',
        'date': 'תאריך',
        'notes': 'הערה',
        'note_placeholder': 'הוסף הערה (אופציונלי)',
        'add': 'הוסף',
        'edit': 'ערוך',
        'delete': 'מחק',
        'cancel': 'בטל',
        'name': 'שם',
        'email': 'דוא"ל',
        'password': 'סיסמה',
        'confirm_password': 'אשר סיסמה',
        'select_language': 'בחר שפה',
        'already_have_account': 'כבר יש לך חשבון? כניסה',
        'create_account': 'צור חשבון',
        'no_transactions': 'אין עסקאות עדיין',
        'no_transactions_desc': 'התחל לעקוב על ידי הוספת עסקה חדשה',
        'no_note': 'ללא הערה',
        'delete_confirm': 'האם אתה בטוח שברצונך למחוק עסקה זו?',
        'cat_food': 'אוכל',
        'cat_transport': 'תחבורה',
        'cat_home': 'בית',
        'cat_shopping': 'קניות',
        'cat_health': 'בריאות',
        'cat_other': 'אחר',
        'add_transaction_desc': 'הוסף הוצאה או הכנסה למעקב פיננסי',
        'edit_transaction': 'ערוך עסקה',
        'edit_transaction_desc': 'עדכן את פרטי העסקה',
        'or': 'או',
        'login_with_google': 'כניסה עם Google',
        'register_with_google': 'הרשמה עם Google',
        'stats': 'סטטיסטיקה',
        'transactions': 'עסקאות',
        'top_category': 'קטגוריה מובילה',
        'data_export': 'ייצוא נתונים',
        'export_json': 'ייצוא ל-JSON',
        'change': 'שנה',
        'currency': 'מטבע',
        'welcome_title': 'ברוכים הבאים ל-FlowMoney',
        'welcome_lead': 'עקוב אחר הוצאותיך, הצג את ההוצאות ועמוד ביעדים.',
        'go_to_dashboard': 'עבור ללוח המחוונים',
        'chart_by_category': 'לפי קטגוריה',
        'chart_income_vs_expenses': 'הכנסות מול הוצאות',
        'no_expense_data': 'אין נתוני הוצאות',
        'no_data': 'אין נתונים',
        'current_currency': 'מטבע נוכחי',
        'current_theme': 'ערכת נושא נוכחית',
        'toggle_theme': 'החלף ערכת נושא',
        'categories': 'קטגוריות',
        'add_category': 'שם קטגוריה חדשה',
        'category_exists': 'הקטגוריה כבר קיימת',
        'category_in_use': 'הקטגוריה בשימוש בעסקאות',
        'category_default': 'לא ניתן למחוק קטגוריה ברירת מחדל',
        'update_app': 'עדכן אפליקציה',
        'auto': 'אוטומטי',
    }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
    const [language, setLanguageState] = useState<Language>(() => {
        const saved = localStorage.getItem('language') as Language;
        return saved || 'en';
    });

    useEffect(() => {
        localStorage.setItem('language', language);
        document.documentElement.lang = language;
        document.documentElement.dir = language === 'he' ? 'rtl' : 'ltr';
    }, [language]);

    const setLanguage = (lang: Language) => {
        setLanguageState(lang);
    };

    const t = (key: string): string => {
        return (translations[language] as Record<string, string>)[key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

// eslint-disable-next-line react-refresh/only-export-components
export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within LanguageProvider');
    }
    return context;
};
